### ISSUE TITLE
Compile programs to wasm for testing

### ISSUE THREAD

**Issue by mrsmkl** [TrueBitFoundation/emscripten-module-wrapper#4]
Various programs could be compiled into wasm. One example is solidity, it can already be compiled with emscripten. Solidity is quite big though, so hopefully there are some smaller, but still useful programs. I tried to compile openssl, but I couldn't run the output with node, it just stalled.

Also the soft FPU code could be compiled with wasdk, and then the FPU instructions could be replaced with functions calls.

**Comment by bloodstalker** [comment]
sami could you explain what you want me to check?
